kind: Service
apiVersion: v1
metadata:
  name: rvstore-ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 30090
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-product-api
spec:
  selector:
    app: product-api
  ports:
  - protocol: TCP
    port: 9001
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-auth-api
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 9003
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-order-api
spec:
  selector:
    app: order-api
  ports:
    - protocol: TCP
      port: 9002
      nodePort: 30091
  type: NodePort